apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector: 
    matchLabels:
      app: goserver 
  replicas: 3
  template:
    metadata: 
      labels: 
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "brsds2000/hello-go:v5.4"

          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1 
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 1

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
      
      volumes:
        - name: config 
          configMap:
            name: configmap-family
            items:
            - key: members 
              path: "family.txt"